import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils";
import { Footer } from "@/components/layout/Footer";
export const metadata = {
  title: "Dolphin DAO by MECHA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, " flex flex-col")}>
        {/* <Providers> */}
        <div className="z-1">
          {/* <Navbar /> */}
          <main className="">{children}</main>
        </div>
        <Footer />
        {/* </Providers> */}
      </body>
    </html>
  );
}
